name: Join the project
description: Request to join UTA Simulation Specification
title: "Join request: <your-username>"
labels: ["join", "triage"]
body:
  - type: input
    id: github_username
    attributes: { label: GitHub username }
    validations: { required: true }
  - type: dropdown
    id: role
    attributes:
      label: Desired role
      options: ["Contributor", "Maintainer - area lead", "Docs"]
  - type: textarea
    id: skills
    attributes: { label: Skills - languages - domain knowledge }
  - type: input
    id: timezone
    attributes: { label: Timezone }
  - type: input
    id: availability
    attributes: { label: Hours per week }
  - type: checkboxes
    id: agreements
    attributes:
      label: Agreements
      options:
        - label: I accept the Code of Conduct
          required: true
        - label: I will follow CONTRIBUTING.md
          required: true
